# Generated by Django 4.0.4 on 2022-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_sheikhs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheikh_name', models.CharField(max_length=200)),
                ('lecture_name', models.CharField(max_length=300)),
                ('lecture_date', models.DateTimeField()),
                ('lecture_image', models.ImageField(upload_to='l_pic')),
                ('lecture_video', models.FileField(upload_to='l_video')),
            ],
        ),
    ]
