# Generated by Django 4.0.6 on 2022-08-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daawa', '0002_all_sheikhs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Islam_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheikh_name', models.CharField(max_length=200)),
                ('serie_lecture_name', models.CharField(max_length=300)),
                ('serie_lecture_date', models.DateTimeField()),
                ('serie_lecture_image', models.ImageField(upload_to='l_pic')),
                ('serie_lecture_video', models.FileField(upload_to='l_video')),
            ],
        ),
    ]
